name: Publish @fxbar/styles

on:
  push:
    tags:
      - 'styles-*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn workspace @fxbar/styles build

      - name: Publish
        run: yarn workspace @fxbar/styles publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
